/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.codenarc.tool

import org.codenarc.test.AbstractTestCase
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

/**
 * Tests that the files generated by GenerateAll and checked into the project are up to date.
 * Regenerates all of them into a temporary directory and compares them to the checked-in files.
 *
 * @author Leonard Brünings
  */
class GeneratedFilesUpToDateTest extends AbstractTestCase {

    private File temporaryDirectory

    /** The checked-in file for each generated file, keyed by the name it is regenerated under */
    private Map<String, String> checkedInFiles = [
        (GenerateCodeNarcRulesProperties.PROPERTIES_FILE): null,
        (GenerateRuleSetAllRules.RULESET_FILE): null,
        (GenerateRuleSetAllRulesByCategory.RULESET_FILE): null,
        (GenerateRuleIndexPages.RULE_INDEX_BY_CATEGORY_FILE): null,
        (GenerateRuleIndexPages.RULE_INDEX_BY_NAME_FILE): null,
    ]

    @BeforeEach
    void setUpGeneratedFilesUpToDateTest() {
        temporaryDirectory = File.createTempDir('GeneratedFilesUpToDateTest', null)
        checkedInFiles.keySet().each { checkedInFile ->
            checkedInFiles[checkedInFile] = regeneratedPathFor(checkedInFile)
        }

        // Redirect every generated file, so that running the generators cannot touch the checked-in ones
        GenerateCodeNarcRulesProperties.propertiesFile = checkedInFiles[GenerateCodeNarcRulesProperties.PROPERTIES_FILE]
        GenerateRuleSetAllRules.ruleSetFile = checkedInFiles[GenerateRuleSetAllRules.RULESET_FILE]
        GenerateRuleSetAllRulesByCategory.ruleSetFile = checkedInFiles[GenerateRuleSetAllRulesByCategory.RULESET_FILE]
        GenerateRuleIndexPages.ruleIndexByCategoryFile = checkedInFiles[GenerateRuleIndexPages.RULE_INDEX_BY_CATEGORY_FILE]
        GenerateRuleIndexPages.ruleIndexByNameFile = checkedInFiles[GenerateRuleIndexPages.RULE_INDEX_BY_NAME_FILE]
    }

    @AfterEach
    void tearDownGeneratedFilesUpToDateTest() {
        GenerateCodeNarcRulesProperties.propertiesFile = GenerateCodeNarcRulesProperties.PROPERTIES_FILE
        GenerateRuleSetAllRules.ruleSetFile = GenerateRuleSetAllRules.RULESET_FILE
        GenerateRuleSetAllRulesByCategory.ruleSetFile = GenerateRuleSetAllRulesByCategory.RULESET_FILE
        GenerateRuleIndexPages.ruleIndexByCategoryFile = GenerateRuleIndexPages.RULE_INDEX_BY_CATEGORY_FILE
        GenerateRuleIndexPages.ruleIndexByNameFile = GenerateRuleIndexPages.RULE_INDEX_BY_NAME_FILE

        temporaryDirectory.deleteDir()
    }

    @Test
    void testGeneratedFilesAreUpToDate() {
        GenerateAll.main(null)

        def outOfDateFiles = checkedInFiles.findAll { checkedInFile, regeneratedFile ->
            new File(checkedInFile).text != new File(regeneratedFile).text
        }

        assert outOfDateFiles.isEmpty(), 'These generated files are out of date; run "./gradlew generateAll" ' +
            "and commit the result: ${outOfDateFiles.keySet().join(', ')}"
    }

    private String regeneratedPathFor(String checkedInFile) {
        new File(temporaryDirectory, new File(checkedInFile).name).path
    }

}
